version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "postgres_server"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: